"""added_user_forigen_key

Revision ID: 91d8fa961a23
Revises: 4563610ca6d7
Create Date: 2026-01-17 13:41:49.516513

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91d8fa961a23"
down_revision: Union[str, Sequence[str], None] = "4563610ca6d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_logs", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_audit_logs_user_id_user"), "audit_logs", "user", ["user_id"], ["uuid"]
    )
    op.add_column("chunks", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_chunks_user_id_user"), "chunks", "user", ["user_id"], ["uuid"]
    )
    op.add_column("conversations", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_conversations_user_id_user"),
        "conversations",
        "user",
        ["user_id"],
        ["uuid"],
    )
    op.add_column("files", sa.Column("user_id", sa.UUID(), nullable=True))

    op.create_foreign_key(
        op.f("fk_files_user_id_user"), "files", "user", ["user_id"], ["uuid"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_uuid"), "user", type_="unique")
    op.drop_constraint(op.f("fk_files_user_id_user"), "files", type_="foreignkey")
    op.drop_constraint(op.f("uq_files_file_hash"), "files", type_="unique")
    op.create_unique_constraint(
        op.f("files_file_hash_key"),
        "files",
        ["file_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("files", "user_id")
    op.drop_constraint(
        op.f("fk_conversations_user_id_user"), "conversations", type_="foreignkey"
    )
    op.drop_column("conversations", "user_id")
    op.drop_constraint(op.f("fk_chunks_user_id_user"), "chunks", type_="foreignkey")
    op.drop_column("chunks", "user_id")
    op.drop_constraint(
        op.f("fk_audit_logs_user_id_user"), "audit_logs", type_="foreignkey"
    )
    op.drop_column("audit_logs", "user_id")
    # ### end Alembic commands ###
