"""added_unique_contraint

Revision ID: 9a1e0817f04e
Revises: 91d8fa961a23
Create Date: 2026-01-20 12:39:02.063239

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a1e0817f04e"
down_revision: Union[str, Sequence[str], None] = "91d8fa961a23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_files_file_hash"), "files", type_="unique")
    op.drop_constraint(op.f("uq_user_email"), "user", type_="unique")
    op.drop_constraint(op.f("uq_user_username"), "user", type_="unique")
    op.create_unique_constraint(
        "uq_file_hash_user_id", "files", ["file_hash", "user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f("uq_file_hash_user_id"), "files", type_="unique")
    op.create_unique_constraint(
        op.f("uq_user_username"),
        "user",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_user_email"), "user", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("uq_files_file_hash"),
        "files",
        ["file_hash"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
